# Change these first
owner: ananthb # Your GitHub organization or username, where this repository lives
repo: apps.kedi.dev # The name of this repository

sites:
  - name: Immich
    url: https://imm.tail42937.ts.net
  - name: Seafile
    url: https://sf.tail42937.ts.net
  - name: Jellyfin
    url: https://tv.tail42937.ts.net
  - name: Jellyseerr
    url: https://watch.tail42937.ts.net
  - name: Actual Budget
    url: https://ab.tail42937.ts.net
  - name: Radicale
    url: https://cal.tail42937.ts.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: apps.kedi.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KEDI Applications
  introTitle: "KEDI Applications Status"
  introMessage: |
    Status page for various applications hosted by Ananth.
  navbar:
    - title: Status
      href: /
    - title: Issues
      href: https://github.com/ananthb/apps.kedi.dev/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
